Fix search-analytics-data-load
This fixes a bug introduced in 3eacc88ee0c6979cad91bb2f7a72214b7f91a6c3.

Setting StringIO.pos = 0 is forbidden and results in a
error: Errno::ESPIPE: Illegal seek @ rb_io_set_pos - <STDIN>

Using rewind is also not permitted, since we are reading from data
that is being piped in.

The workaround is to store the stream as a temp file, this seems
like the nicest way to do it! This lets us rewind.

Trello: https://trello.com/c/Q4nK0icC/828