Fix default hash value keyword arguments conflict
This piece of code sets a default value for when you look up an item and
the hash doesn't have a value. In Ruby 3.4 we have to specify a default
hash value as an explicit hash, omitting the braces caused the arguments
to be treated as keyword arguments and an error is raised:

```
 ArgumentError: unknown keywords: :rank, :view_count
```